### ISSUE TITLE
How to use drawbridge with embedded nREPL server?

### ISSUE THREAD

**Issue by hasnainnaeem** [nrepl/drawbridge#47]
I'm working with a Compjure codebase and embedding a nREPL server with custom middleware as instructed here: 
https://nrepl.org/nrepl/usage/server.html

Cod example:
`(nrepl.server/start-server :port 7888 :handler (custom-nrepl-handler))`

Since I am new to Drawbridge, I have two questions:
1. Will the drawbridge seamlessly work with the embedded server? 
2. If yes, how will the setup look like?

**Comment by hasnainnaeem** [comment]
It appears it's fairly simple to use it with embedded server. Closing the issue.

**Comment by bbatsov** [comment]
For the record I'll link here the transport docs, as Drawbridge is just another nREPL transport https://nrepl.org/nrepl/design/transports.html#edn-transport
